version: "3.9"

services:
  dpe-dashboard-tool:
    build: 
      context: . # DPE-Energy-Performance-Analysis-API/.
      dockerfile: Dockerfile
    image: dpe-dashboard:local
    container_name: dpe-dashoard-cont
    ports:
      - 8501:8501
    environment:
      SERVER_API_URL: http://host.docker.internal:8000 # updta docker
      S3_URL: host.docker.internal:9000
      S3_ACCESS_KEY: xxxxx
      S3_SECRET_KEY: xxxxx
      S3_BUCKET_NAME: dpe-storage-v1
    networks:
      - dpe-bridge

networks:
  dpe-bridge:
    driver: bridge